protogen:           ## go stubs/files based on protoc definition
	@protoc --go_out=../internal --go_opt=module=microservice-exercise/internal --go-grpc_out=../internal --go-grpc_opt=module=microservice-exercise/internal ./*.proto
